### PR TITLE
 Feature: Cropping image according to bounding boxes detected by Yolo

### PR DESCRIPTION
**Pull request by Louayarfaoui95**
This feature uses an XML file where the ouput of Yolo inference is stocked. The XML file format is the same as the one used for training. 
Preference: Test this outside of the dev container for review, you already have a testing XML file and some images that was used to train OCR model.   Tests on the dev container will be welcomed if it works. 
When testing don't forget to install the libs and frameworks used
**Remarks**: The third image used in test demonstrates the robustness of this feature when changing the detection angle.

### CODE REVIEW

**Comment by Louayarfaoui95** [comment]
No XML file will be used after the integration within ROS2. This is only used for testing purposes when implementing the pipeline before embedding it. 
After the ROS2 integration, the detection node (image pre processing+ Yolov8 inference) will publish the bounding boxes to a topic to which the second node ( image cropping, filtering, OCR inference) will subscribe to get the bounding box. Data can deleted after if needed.

**Review by emmacstn — APPROVED** [review]
Great job  :)

**Comment by Louayarfaoui95** [comment]
No XML file will be used after the integration within ROS2. This is only used for testing purposes when implementing the pipeline before embedding it. 
After the ROS2 integration, the detection node (image pre processing+ Yolov8 inference) will publish the bounding boxes to a topic to which the second node ( image cropping, filtering, OCR inference) will subscribe to get the bounding box. Data can deleted after if needed.

**Comment by Louayarfaoui95** [comment]
Merged.

**Pull request merged**
